ecommerce/authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
]

ecommerce/cart/api/urls.py
from rest_framework.routers import DefaultRouter
from .views import CartViewSet

cart_router = DefaultRouter()
cart_router.register(r"cart", CartViewSet)

ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path("my-cart/<str:username>/", views.cart, name="my-cart"),
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
]

ecommerce/ecommerce/api/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from product.api.urls import product_router
from cart.api.urls import cart_router

router = DefaultRouter()

router.registry.extend(product_router.registry)
router.registry.extend(cart_router.registry)

urlpatterns = [
    path("", include(router.urls)),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include("ecommerce.api.urls")),
    path("", include("home.urls")),
    path("product/", include("product.urls")),
    path("auth/", include("authentication.urls")),
    path("cart/", include("cart.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/product/api/urls.py
from rest_framework.routers import DefaultRouter
from .views import ProductViewSet

product_router = DefaultRouter()
product_router.register(r"product", ProductViewSet)

ecommerce/product/urls.py
from django.urls import path
from . import views

app_name = "product"
urlpatterns = [
    path("<int:id>/", views.product, name="product"),
]

ecommerce/cart/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Cart(models.Model):
    name = models.CharField(max_length=100)
    roast = models.CharField(max_length=100)
    size = models.CharField(max_length=100)
    quantity = models.CharField(max_length=2)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.roast} {self.size} {self.quantity} {self.price}"

ecommerce/product/models.py
from django.db import models

# Create your models here.

ROAST_CHOICES = (
    ("light", "light"),
    ("medium", "medium"),
    ("dark", "dark"),
)

SIZE_CHOICE = (
    ("12", "12oz"),
    ("16", "16oz"),
    ("32", "32oz"),

)

COFFEE_TYPE_CHOICE = (
    ("decaf", "decaffeinated"),
    ("easy-late", "easy-late"),
    ("flavored", "flavored"),
    ("ground", "ground"),
    ("organic", "organic"),
    ("reserved", "reserved"),
    ("seasonal", "seasonal"),
    ("whole-bean", "whole bean"),
)


class Roast(models.Model):
    roast = models.CharField(choices=ROAST_CHOICES, max_length=20)

    def __str__(self):
        return self.roast


class Size(models.Model):
    size = models.CharField(choices=SIZE_CHOICE, max_length=3)

    def __str__(self):
        return self.size


class CoffeeType(models.Model):
    coffee_type = models.CharField(choices=COFFEE_TYPE_CHOICE, max_length=20)

    def __str__(self):
        return self.coffee_type


class Product(models.Model):
    name = models.CharField(max_length=100)
    roast = models.ManyToManyField(Roast)
    size = models.ManyToManyField(Size)
    coffee_type = models.ManyToManyField(CoffeeType)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to="images/")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

ecommerce/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

ecommerce/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignupForm, LoginForm

# Create your views here.


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)
                return redirect("home:index")

    else:
        form = LoginForm()

    return render(request, "authentication/login.html", {"form": form})


def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("authentication:login")
    else:
        form = SignupForm()

    return render(request, "authentication/signup.html", {"form": form})


def user_logout(request):
    logout(request)
    return redirect("authentication:login")

ecommerce/cart/api/views.py
from rest_framework import viewsets
from .serializers import CartSerializer
from ..models import Cart


class CartViewSet(viewsets.ModelViewSet):
    queryset = Cart.objects.all()
    serializer_class = CartSerializer

ecommerce/cart/views.py
from django.shortcuts import render
from .models import Cart
from django.contrib.auth.models import User

from django.http import JsonResponse
from .models import Cart
from cart.api.serializers import CartSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
# Create your views here.


def cart(request, username):
    user = User.objects.get(username=username)
    cart = Cart.objects.filter(created_by=user.id)

    context = {
        "cart": cart
    }
    return render(request, "cart/cart.html", context)


def add_to_cart(request):
    if request.method == "POST":
        data = request.POST
        name = data["name"]
        roast = data["roast"]
        size = data["size"]
        quantity = data["quantity"]
        price = data["price"]
        image_url = data["image_url"]
        created_by = int(data["created_by"])
        print(created_by)
        user = User.objects.get(id=created_by)

        cart = Cart(name=name, roast=roast, size=size, quantity=quantity,
                    price=price, image_url=image_url, created_by=user)
        cart.save()

    return render(request, "home/index.html")

ecommerce/home/views.py
from django.http import JsonResponse
from django.shortcuts import render

from product.models import Product
from product.api.serializers import ProductSerializer

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

# Create your views here.


@api_view(["GET"])
def product_list(request, format=None):
    if request.method == "GET":
        product = Product.objects.all()
        serializer = ProductSerializer(product, many=True)
        return JsonResponse(serializer.data)


def index(request):
    # 1 - light, 2 - medium, 3 - dark
    filter_roast = 2

    # 1 - 12, 2 - 16, 3 - 32
    filter_size = 2

    # 1 - decaf, 2 - easy-late, 3 - ground, 4 - organic
    # 5 - reserved, 6 - seasonal, 7 - whole-bean
    filter_coffee_type = 2

    product = Product.objects.all()
    if filter_roast:
        product = product.filter(roast__id=filter_roast)
    if filter_size:
        product = product.filter(size__id=filter_size)
    if filter_coffee_type:
        product = product.filter(coffee_type__id=filter_coffee_type)

    context = {
        "product": product
    }

    return render(request, "home/index.html", context)

ecommerce/product/api/views.py
from rest_framework import viewsets
from .serializers import ProductSerializer
from ..models import Product


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

ecommerce/product/views.py
from django.shortcuts import render
from .models import Product

# Create your views here.


def product(request, id):
    product = Product.objects.get(id=id)

    context = {
        "product": product
    }

    return render(request, "product/product.html", context)

ecommerce/authentication/templates/authentication/login.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block content %}

<section>
  <form class="auth-form" method="POST">
    <h1 class="title">Cawpii</h1>
    {% csrf_token %}
    {{ form.as_p }}


    <button class="submit" type="submit">Login</button>

    <span>Don't have an account yet click <a href="{% url 'authentication:signup' %}">here</a></span>
  </form>
</section>

{% endblock content %}

ecommerce/authentication/templates/authentication/signup.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Signup{% endblock title %}
{% block content %}

<section>
  <form class="auth-form" method="POST">
    <h1 class="title">Cawpii</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <button class="submit" type="submit">Signup</button>

    <span>Already have an account click <a href="{% url 'authentication:login' %}">here</a></span>
  </form>
</section>

{% endblock content %}

ecommerce/cart/templates/cart/cart.html
{% extends 'home/base.html' %}
{% load static %}
{% block css%}<link href="{% static 'cart/style.css' %}" rel="stylesheet">{% endblock css%}
{% block title %}My Cart{% endblock title %}
{% block content %}
<section class="cart-container">
  <h1>My Cart</h1>
  {% for item in cart %}
    <div class="item-container">
      <div class="left">
        <input type="checkbox">
        <img src={{item.image_url}}>
        <div class="item-info">
          <h1 class="name">{{item.name}}</h1>
          <p>Roast: {{item.roast}}</p>
          <p>Size: {{item.size}}</p>
        </div>
      </div>

      <div class="right">
        <h1 class="price">$ {{item.price}}</h1>
        <div class="quantity-container">
          <img onclick='minus()' src="{% static 'home/images/minus.png' %}">
           <p id="quantity-counter">1</p>
          <img onclick='add()' src="{% static 'home/images/plus.png' %}">
        </div>
      </div>

    </div>
  {% endfor %}
</section>

<script src="{% static 'cart/script.js' %}"></script>
{% endblock content %}

ecommerce/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
  {% load static %}
  <link href="{% static 'home/style.css' %}" rel="stylesheet">
  {% block css %}{% endblock css %}
  <link rel="icon" type="image/x-icon" href="{% static 'home/images/favicon.ico' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>

<body>
  <nav>
    <div class="left">
      <img class="icon" src="{% static 'home/images/coffee-bean.png' %}">
        <a class="" href={% url 'home:index' %}>Cawpii</a>


    </div>

    <div class="right">
        <a href="#" class="user">
          <img src="{% static 'home/images/user.png' %}" >
          {% if request.user.is_authenticated %}
            <p>{{ request.user.username }}</p>
          {% endif %}
        </a>

        <a class="cart" href="{% url 'cart:my-cart' username=request.user.username %}">
          <img src="{% static 'home/images/shopping-bag.png' %}" >
          
        </a>

    </div>
  </nav>

  {% block content %}
  {% endblock content %}



</body>
</html>

ecommerce/home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Cawpii{% endblock title %}
{% block content %}
  <section>
    <div class="title">
      <img src="{% static 'home/images/coffee-beans-1.png' %}">
      <h1>Browse Our Coffee</h1>
      <img src="{% static 'home/images/coffee-beans-1.png' %}">
    </div>

    <div class="container-grid">

      <div class="items">
        <div class="filter-container">

          <div class="filter">
            <label for="filter-options">Roast :</label>
            <select id="roast-filter">
              <option value="0">All</option>
              <option value="1">Light</option>
              <option value="2">Medium</option>
              <option value="3">Dark</option>
            </select>
          </div>

          <div class="filter">
            <label for="filter-options">Size :</label>
            <select id="size-filter">
              <option value="0">All</option>
              <option value="1">12oz</option>
              <option value="2">16oz</option>
              <option value="3">32oz</option>
            </select>
          </div>

          <div class="filter">
            <label for="filter-options">Type :</label>
            <select id="coffee-type-filter">
              <option value="0">All</option>
              <option value="1">Decaffeinated</option>
              <option value="2">Easy-late</option>
              <option value="3">Flavored</option>
              <option value="4">Ground</option>
              <option value="5">Organic</option>
              <option value="6">Reserved</option>
              <option value="7">Seasonal</option>
              <option value="8">Whole Bean</option>
            </select>
          </div>

          <div class="filter">
          <label for="filter-options">Sory By :</label>
          <select onchange='filter_options()' id="filter-options" name="filter">
            <option value="featured">Featured</option>
            <option value="high-to-low">High to Low</option>
            <option value="low-to-high">Low to High</option>
          </select>
          </div>

        </div>

        <div id="item-container" class="item-container">

        </div>

      </div>
    </div>
  </section>

<script src="{% static 'home/script.js' %}"></script>
{% endblock content %}