social-media/authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
    path("logout/", views.logout_view, name="logout"),
]

social-media/community/api/urls.py
from rest_framework.routers import DefaultRouter
from .views import PostViewSet

post_router = DefaultRouter()
post_router.register(r'post', PostViewSet)

social-media/community/urls.py
from django.urls import path
from . import views

app_name = "community"
urlpatterns = [
    path("", views.community, name="community"),
    path("create-post/", views.create_post, name="create_post"),

    path("like-post/", views.like_post, name="like_post"),
]

social-media/core/api/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from community.api.urls import post_router

router = DefaultRouter()

# app 1
# app 2
# customers

router.registry.extend(post_router.registry)

urlpatterns = [
    path("", include(router.urls)),
]

social-media/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("community/", include("community.urls")),
    path("", include("authentication.urls")),

    path("api/", include('core.api.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social-media/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
]

social-media/home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
]

social-media/community/models.py
from django.db import models
from django.contrib.auth.models import User
from user_profile.models import Profile
import json

# Create your models here.

VISIBILITY_CHOICE = (
    ("public", "public"),
    ("private", "private"),
    ("friends", "friends"),
)


class Post(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    visibility = models.CharField(choices=VISIBILITY_CHOICE, max_length=10)
    date_created = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=3000)
    image = models.ImageField(upload_to="images/", blank=True)
    likes = models.IntegerField()
    comments = models.CharField(max_length=3000)
    shares = models.IntegerField()

    def get_comments(self):
        return json.loads(self.comments)

    def set_comments(self, x):
        self.comments = json.dumps(x)

    def __str__(self):
        return f"{self.profile.user.username} {self.date_created}"

social-media/dashboard/models.py
from django.db import models

# Create your models here.

social-media/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
# from community.models import Post

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile = models.ImageField(upload_to="images/profile/", blank=True)
    about_me = models.CharField(max_length=1000, blank=True)
    followers = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True,
    )

    def __str__(self):
        return self.user.username

social-media/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))

    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))

social-media/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignupForm, LoginForm
from user_profile.models import Profile
# Create your views here.


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)

                return redirect("community:community")

    else:
        form = LoginForm()

    context = {
        "form": form
    }

    return render(request, "authentication/login.html", context)


def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid:
            form.save()

            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)
                profile = Profile(user=user)
                profile.save()

                return redirect("community:community")

    else:
        form = SignupForm()

    context = {
        "form": form
    }
    return render(request, "authentication/signup.html", context)


def logout_view(request):
    logout(request)
    return redirect("home:index")

social-media/community/api/views.py
from rest_framework import viewsets
from .serializers import PostSerializer
from ..models import Post


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

social-media/community/views.py
from django.shortcuts import render, redirect
from .models import Post
from user_profile.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.http import JsonResponse

from datetime import datetime


# Create your views here.


@login_required(login_url="/login/")
def community(request):
    posts = Post.objects.all().order_by("-date_created")
    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user.id)

    else:
        profile = ""

    context = {
        "posts": posts,
        "profile": profile,
    }

    return render(request, "community/community.html", context)


def create_post(request):

    if request.method == "POST":
        if request.user.is_authenticated:

            data = request.POST
            profile = Profile.objects.get(user=data["user"])
            visibility = "public"
            text = data["text"]
            if request.FILES["image"]:
                date_now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                image = request.FILES["image"]
                image.name = date_now+image.name

            else:
                image = ""

            likes = 0
            comments = "0"
            shares = 0

            post = Post(
                profile=profile, visibility=visibility,
                text=text, image=image, likes=likes,
                comments=comments, shares=shares)

            post.save()

            return redirect("community:community")

# TODO: Please build this tomorrow haha


def like_post(request):
    if request.method == "POST":
        return JsonResponse({"status": "ok"})


def comment_post(request):
    pass


def share_post(request):
    pass

social-media/dashboard/views.py
from django.shortcuts import render
from user_profile.models import Profile

# Create your views here.


def dashboard(request):
    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user.id)

    else:
        profile = ""

    context = {
        "profile": profile
    }
    return render(request, "dashboard/dashboard.html", context)

# TODO: do this after you finish the community todo


def change_profile(request):
    pass


def change_about_me(request):
    pass

social-media/home/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "home/index.html")

social-media/user_profile/views.py
from django.shortcuts import render

# Create your views here.

social-media/authentication/templates/authentication/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>D-Whale - Login</title>
  {% load static %}
  <link rel="icon" type="image/x-icon" href="{% static 'core/images/favicon.ico' %}">
  <link href="{% static 'authentication/style.css' %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
</head>

<body>
  <section>
    <div class="left">
      <a href="{% url 'home:index' %}">
        <img src="{% static 'core/images/arona-whale.png' %}">
      </a>
      <h1>Welcome To <span>D-Whale</span></h1>
      <p>Hang out anytime, anywhere <span>D-Whale</span>
        makes it easy and fun to stay close yo
        your favorite people.</p>
    </div>

    <div class="right">
      <form method="post">
        <h1>Login</h1>

        {% csrf_token %}
        {{form.as_p}}
        <button class="primary-btn" type="submit">Login</button>
      </form>

      <div class="here">
        <span>Don't have an account yet click <a href="{% url 'authentication:signup' %}">here</a></span>
      </div>
    </div>


  </section>
</body>

</html>

social-media/authentication/templates/authentication/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>D-Whale - Signup</title>
  {% load static %}
  <link rel="icon" type="image/x-icon" href="{% static 'core/images/favicon.ico' %}">
  <link href="{% static 'authentication/style.css' %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
</head>

<body>
  <section>
    <div class="left">
      <a href="{% url 'home:index' %}">
        <img src="{% static 'core/images/arona-whale.png' %}">
      </a>
      <h1>Welcome To <span>D-Whale</span></h1>
      <p>Hang out anytime, anywhere <span>D-Whale</span>
        makes it easy and fun to stay close yo
        your favorite people.</p>
    </div>

    <div class="right">
      <form method="post">
        <h1>Signup</h1>

        {% csrf_token %}
        {{form.as_p}}
        <button class="primary-btn" type="submit">Login</button>
      </form>

      <div class="here">
        <span>Already have an account click <a href="{% url 'authentication:login' %}">here</a></span>
      </div>
    </div>


  </section>
</body>

</html>

social-media/community/templates/community/community.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}D-Whale{% endblock title %}
{% block css %}
<link href="{% static 'community/style.css' %}" rel="stylesheet">{% endblock css %}
{% block content %}

<section class="content">
  <h1 class="at">Community</h1>
  <div class="greet">
    <h1>Hello, {{request.user.username}}!</h1>
    <p>What's new with you? Would you like to share something?</p>
  </div>


  <form class="create-post" method="post" action="{% url 'community:create_post' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Create Post</h3>
    <div class="message-container">
      <div class="icon-container"><img src="{% static 'core/images/messenger.png' %}"> </div>
      <textarea name="text" placeholder="What's up, {{request.user.username}}?"></textarea>
    </div>
    <div>
      <img id="preview-img">
    </div>
    <div class="create-post-container">
      <div class="image-video-container">
        <div class="flex-row">
          <label for="upload-image" class="label-icon-container pointer">
            <img src="{% static 'core/images/photo.png' %}">
            <span>Image</span>
            <input type="file" onchange='preview_image()' id="upload-image" name="image" style="display:none">
          </label>
        </div>
        <div class="flex-row">
          <label class="label-icon-container">
            <img src="{% static 'core/images/video.png' %}"> 
            <span>Video</span>
          </label>
        </div>
      </div>

      <input type="none" name="user" value={{user.id}} style="display:none">

      <button class="primary-icon-btn" type="submit">
        <img src="{% static 'core/images/paper-plane.png' %}">
        <span>Post</span>
      </button>
    </div>
  </form>

  {% include 'community/posts.html' %}
</section>
{% endblock content %}

{% block script %}
<script src="{% static 'community/script.js' %}"></script>
{% endblock script %}

social-media/community/templates/community/posts.html
{% load static %}
{% for post in posts %}
<div class="post-container">
  <div class="header">
    <div class="user-info">
      {% if post.profile.profile.url != "" %}
        <img class="user" src="{{post.profile.profile.url}}">
      {% else %}
        <img class="user" src="{% static 'core/images/user-icon.png' %}">
      {% endif %}

      <div>
        <h3 class="name">{{post.profile.user.username}}</h3>
        <span class="time">{{post.date_created}} | {{post.visibility}}</span>
      </div>
    </div>
    <img class="dots" src="{% static 'core/images/dots.png' %}">
  </div>

  <div class="body">
    <p>{{post.text}}</p>
    {% if post.image.url != "" %}
    <img class="post-img" src={{post.image.url}}>
    {% endif %}
  </div>

  <div class="footer">
    <div>
      <form method="POST" id="like-form" onclick='like_post()'>
        <img id="likes-img" src="{% static 'core/images/heart.png' %}">
      </form>
      <p id="likes">{{post.likes}}</p><p>Likes</p>
    </div>

    <div>
      <img id="comment" src="{% static 'core/images/comment.png' %}">
      {{post.comments}} Comments
    </div>

    <div>
      <img id="share" src="{% static 'core/images/share.png' %}">
      {{post.shares}} Share
    </div>
  </div>
</div>
{% endfor %}

{% block script %}
<script src="{% static 'community/posts.js' %}"></script>
{% endblock script %}

social-media/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <title>{% block title %}{% endblock title %}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'core/images/favicon.ico' %}">
  <link href="{% static 'core/style.css' %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

  {% block css %}{% endblock css %}
</head>

<body>
  {% include 'core/sidebar.html' %}
  <section>
    <header>
      <div><img src="{% static 'core/images/search.png' %}"></div>
      <div><img src="{% static 'core/images/bell.png' %}"></div>
        <a href="{% url 'dashboard:dashboard' %}">
          {% if profile.profile.url != "" %}
          <img class="user" src="{{profile.profile.url}}">
          {% else %}
            <img class="user" src="{% static 'core/images/user-icon.png' %}">
          {% endif %}
        </a>
    </header>
    {% block content %}{% endblock content %}
  </section>

</body>

  {% include 'core/modal.html' %}
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
{% block script %}{% endblock script %}

</html>

social-media/core/templates/core/modal.html
{% load static %}
<div id="modal" class="modal">
  <form
    class="create-post modal-item" method="post" action="{% url 'community:create_post' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal-header">
      <h3>Create Post</h3>
      <img onclick='close_modal()' src="{% static 'core/images/close.png' %}">
    </div>
    <div class="message-container">
      <div class="icon-container"><img src="{% static 'core/images/messenger.png' %}"> </div>
      <textarea name="text" placeholder="What's up, {{request.user.username}}?"></textarea>
    </div>
    <div>
      <img id="modal-preview-img">
    </div>
    <div class="create-post-container">
      <div class="image-video-container">
        <div class="flex-row">
          <label for="modal-upload-image" class="label-icon-container pointer">
            <img src="{% static 'core/images/photo.png' %}">
            <span>Image</span>
            <input type="file" onchange='modal_preview_image()' id="modal-upload-image" name="image" style="display:none">
          </label>
        </div>
        <div class="flex-row">
          <label class="label-icon-container">
            <img src="{% static 'core/images/video.png' %}"> 
            <span>Video</span>
          </label>
        </div>
      </div>

      <input type="none" name="user" value={{user.id}} style="display:none">

      <button class="primary-icon-btn" type="submit">
        <img src="{% static 'core/images/paper-plane.png' %}">
        <span>Post</span>
      </button>
    </div>
  </form>

</div>
<script src="{% static 'core/modal.js' %}"></script>

social-media/core/templates/core/sidebar.html
{% load static %}
{% block css %}
<link href="{% static 'core/style.css' %}" rel="stylesheet">{% endblock css %}
<nav class="sidebar">
  <div>
    <div class="title-container">
      <img src="{% static 'core/images/arona-whale.png' %}">
      <h1>Welcome to <span>D-Whale</span></h1>
      <p>(Name subject to change)</p>
    </div>

  <div class="navigation">
    <a 
      id="dashboard"
      onmouseover='nav_mouse_over("dashboard")'
      onmouseleave='nav_mouse_leave("dashboard")'
      href="{% url 'dashboard:dashboard' %}">
      <img id="dashboard-icon" src="{% static 'core/images/dashboard.png' %}">
      Dashboard
    </a>

    <a
      id="community"
      onmouseover='nav_mouse_over("community")'
      onmouseleave='nav_mouse_leave("community")'
      href="{% url 'community:community' %}">
      <img id="community-icon" src="{% static 'core/images/selected-community.png' %}">
      Community
    </a>

    <a
      id="chat"
      onmouseover='nav_mouse_over("chat")'
      onmouseleave='nav_mouse_leave("chat")'
      href="#">
      <img id="chat-icon" src="{% static 'core/images/bubble-chat.png' %}">
      Chat
    </a>

    <a
      id="settings"
      onmouseover='nav_mouse_over("settings")'
      onmouseleave='nav_mouse_leave("settings")'
      href="#">
      <img id="settings-icon" src="{% static 'core/images/settings.png' %}">
      Settings
    </a>
  </div>
  </div>

  <div onclick="open_modal()" class="primary-icon-btn">
    <img src="{% static 'core/images/plus.png' %}">
    <span>Create a post</span>
  </div>
</nav>

<script src="{% static 'core/script.js' %}"></script>

social-media/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}D-Whale - Dashboard{% endblock title %}
{% block css %}
<link href="{% static 'dashboard/style.css' %}" rel="stylesheet">{% endblock css %}
{% block content %}
<section class="dashboard">
  <h1 class="at">Dashboard</h1>
  <div>
    <div class="user">
      {% if profile.profile.url != "" %}
        <img src={{profile.profile.url}}>
      {% else %}
      <img src={% static 'core/images/user-icon.png' %}>
      {% endif %}
      <div>
        <h1 class="name">{{profile.user.username}}</h1>
        <p class="about-me">{{profile.about_me}}</p>
      </div>

      <div class="followers-post-container">
        <h1>Followers {{profile.followers|length}}</h1>
        <h1>Posts 0</h1>
      </div>


    </div>
  </div>


  <div class="logout">
    <a href="{% url 'authentication:logout' %}">Logout</a>
  </div>


</section>
{% endblock content %}

social-media/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <title>D-Whale</title>
  <link rel="icon" type="image/x-icon" href="{% static 'core/images/favicon.ico' %}">
  <link href="{% static 'home/style.css' %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
</head>

<body>
    <section>
      <img src="{% static 'core/images/arona-whale.png' %}">
      <h1>Welcome To <span>D-Whale</span></h1>
      <p>Hang out anytime, anywhere <span>D-Whale</span>
      makes it easy and fun to stay close yo
      your favorite people.</p>
      <div class="login-signup-container">
        <a class="login" href="{% url 'authentication:login' %}">Login</a>
        <a class="signup" href="{% url 'authentication:signup' %}">Signup</a>
      </div>
    </section>

</body>
</html>